{{- if ne .Values.global.mode "quickstart" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-cm
data:
  {{- with .Values.mysql }}
  mysql.db.name: {{ .mysqlDatabase }}
  mysql.port: "3306"
  mysql.user: {{ .mysqlUser }}
  mysql.password: {{ .mysqlPassword }}
  {{- end }}
{{- end }}
