apiVersion: v1
appVersion: "1.0"
description: use helm to deloy nacos cluster.
home: https://nacos.io/en-us/
icon: https://nacos.io/img/nacos.png
maintainers:
- email: huangmnlove@163.com
  name: arrowfeng
name: nacos
sources:
- https://github.com/nacos-group/nacos-k8s
version: 0.1.1
